In [1]:
import torch
import cv2
import pandas as pd
import numpy as np

c:\Users\Alpha 15 A3DD\AppData\Local\Programs\Python\Python37\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
# # Image
im = 'https://ultralytics.com/images/zidane.jpg'
results = model(im)

Using cache found in C:\Users\Alpha 15 A3DD/.cache\torch\hub\ultralytics_yolov5_master
YOLOv5  2023-5-6 Python-3.7.4 torch-1.13.1+cpu CPU

Fusing layers... 


requirements: C:\Users\Alpha 15 A3DD\.cache\torch\hub\requirements.txt not found, check failed.


YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape... 


In [15]:
haha = cv2.imread('test_data\zidane.jpg')
cv2.imshow('fdsfas',haha)
cv2.waitKey(0) & 0xFF == ord('q')
cv2.destroyAllWindows()

In [3]:
res = results.pandas().xyxy[0]
res

xmin        ymin         xmax        ymax  confidence  class    name
0  743.290405   48.343658  1141.756592  720.000000    0.879861      0  person
1  441.989624  437.336731   496.585083  710.036194    0.675119     27     tie
2  123.051117  193.238068   714.690796  719.771240    0.666693      0  person
3  978.989807  313.579468  1025.302856  415.526184    0.261517     27     tie

In [34]:
def plot_boxes(frame, res):
    res = res.pandas().xyxy[0]
    n = len(res)
    for i in range(n):
        # xmin, ymin, xmax, ymax = res['xmin'][i], res['ymin'][i], res['xmax'][i], res['ymax'][i]
        xmin, ymin, xmax, ymax = int(res['xmin'][i]), int(res['ymin'][i]), int(res['xmax'][i]), int(res['ymax'][i])
        print( xmin, ymin, xmax, ymax)
        box_color = (0,0,255)
        cv2.rectangle(frame, (xmin,ymin),(xmax,ymax),box_color,2)
        cv2.putText(frame, res['name']+str(np.round(res['confidence'][i],2)), (xmin,ymin-10), cv2.FONT_HERSHEY_SIMPLEX, 1, box_color, thickness=2)
    return frame

In [4]:
labels, cord = results.xyxyn[0][:, -1], results.xyxyn[0][:, :-1]

In [5]:
labels

tensor([ 0., 27.,  0., 27.])

In [6]:
cord

tensor([[0.58070, 0.06714, 0.89200, 1.00000, 0.87986],
        [0.34530, 0.60741, 0.38796, 0.98616, 0.67512],
        [0.09613, 0.26839, 0.55835, 0.99968, 0.66669],
        [0.76484, 0.43553, 0.80102, 0.57712, 0.26152]])

In [10]:
for *boxes, conf in cord:
    print(boxes,conf,'test boxes[0]',boxes[0].item())

[tensor(0.58070), tensor(0.06714), tensor(0.89200), tensor(1.)] tensor(0.87986) test boxes[0] 0.580695629119873
[tensor(0.34530), tensor(0.60741), tensor(0.38796), tensor(0.98616)] tensor(0.67512) test boxes[0] 0.345304399728775
[tensor(0.09613), tensor(0.26839), tensor(0.55835), tensor(0.99968)] tensor(0.66669) test boxes[0] 0.09613368660211563
[tensor(0.76484), tensor(0.43553), tensor(0.80102), tensor(0.57712)] tensor(0.26152) test boxes[0] 0.764835774898529


In [ ]:
haha = cv2.imread('test_data\zidane.jpg')
pred = model(haha)
cv2.imshow('RESULT!!',plot_boxes(haha, pred))
cv2.waitKey(0) & 0xFF == ord('q')
cv2.destroyAllWindows()

In [40]:
classes = model.names

In [46]:
def class_to_label(x):
    return classes[int(x)]

def plot_boxes(results, frame):
    results = results.xyxyn[0][:, -1], results.xyxyn[0][:, :-1]
    labels, cord = results
    n = len(labels)
    x_shape, y_shape = frame.shape[1], frame.shape[0]
    for i in range(n):
        row = cord[i]
        if row[4] >= 0.3:
            x1, y1, x2, y2 = int(row[0]*x_shape), int(row[1]*y_shape), int(row[2]*x_shape), int(row[3]*y_shape)
            bgr = (0, 255, 0)
            cv2.rectangle(frame, (x1,y1-15), (x2,y2), bgr, 2)
            cv2.putText(frame, class_to_label(labels[i]), (x1,y1), cv2.FONT_HERSHEY_SIMPLEX, 0.9, bgr, thickness=2)
    return frame

In [24]:
import os
import time
from datetime import datetime
os.path.join('txt', datetime.now().strftime("%Y%m%d%H%M%S"))

'txt\\20230506180838'

In [72]:
time.strftime("%d%m%y%H%M%S")

'060523225740'

In [47]:
os.path.join('sort_file_text','log_new_text')

'sort_file_text\\log_new_text'

In [75]:
with open(f'sort_file_text\\log_text_{strftime("%d%m%y")}.txt', 'a') as f:
    f.write('heloo')

In [47]:
cv2.imshow('resyyy',plot_boxes(pred,haha))
cv2.waitKey(0) & 0xFF == ord('q')
cv2.destroyAllWindows()

In [36]:
# def score_frame(self, frame):
#     self.model.to(self.device)
#     frame = [frame]
#     results = self.model(frame)
#     labels, cord = results.xyxyn[0][:, -1], results.xyxyn[0][:, :-1]
#     return labels, cord

# def class_to_label(self, x):
#     return self.classes[int(x)]

# def plot_boxes(self, results, frame):
#     labels, cord = results
#     n = len(labels)
#     x_shape, y_shape = frame.shape[1], frame.shape[0]
#     for i in range(n):
#         row = cord[i]
#         if row[4] >= 0.3:
#             x1, y1, x2, y2 = int(row[0]*x_shape), int(row[1]*y_shape), int(row[2]*x_shape), int(row[3]*y_shape)
#             bgr = (0, 255, 0)
#             cv2.rectangle(frame, (x1,y1), (x2,y2), bgr, 2)
#             cv2.putText(frame, self.class_to_labelP(labels[i]), (x1,y1), cv2.FONT_HERSHEY_SIMPLEX, 0.9, bgr, thickness=2)
#     return frame

In [59]:
from scipy.optimize import linear_sum_assignment as linear_assignment_sp

In [61]:
sp = linear_assignment_sp(np.array([[4, 1, 3], [2, 0, 5], [3, 2, 2]]))
print(sp)
print(len(sp))

(array([0, 1, 2], dtype=int64), array([1, 0, 2], dtype=int64))
2


In [64]:
sp = np.transpose(np.asarray(sp))

array([[0, 1, 2],
       [1, 0, 2]], dtype=int64)

In [62]:
from sklearn.utils.linear_assignment_ import linear_assignment
sk = linear_assignment(np.array([[4, 1, 3], [2, 0, 5], [3, 2, 2]]))
print(sk)
print(len(sk))

[[0 1]
 [1 0]
 [2 2]]
3


c:\Users\Alpha 15 A3DD\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\utils\linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


In [70]:
tuple(map(int,[2.9,4.1]))

(2, 4)